### ISSUE TITLE
[req] Apple M1 Silicon support

### ISSUE THREAD

**Issue by maxfierke** [maxfierke/mstrap#21]
**Is your feature request related to a problem? Please describe.**
As someone interested in acquiring one of these fancy, new Apple M1 machines, I would like to be able to provision my machine with native ARM software and get this fancy beast of a machine provisioned like my existing amd64 machines.

**Describe the solution you'd like**
Run `mstrap` on an M1 machine without using Rosetta 2

**Describe alternatives you've considered**
Running with Rosetta 2

**Describe how this fits in with the project's aims** (as described [here](https://mstrap.dev/docs/))
N/A

**Checklist**
- [x] I have read the [project aims](https://mstrap.dev/docs/) on the documentation site
- [x] To the best of my knowledge, I am not asking about an existing feature request

---

**Barriers to start**:
- [X] strap.sh support for Big Sur and M1 silicon
- [x] Crystal support for M1 silicon (https://github.com/crystal-lang/crystal/issues/10066)
  - ~~Works, but compiler has to be cross-compiled on an M1 machine with the x86_64 version linked to LLVM 11 in order to get a working arm64 build of the compiler. It's a pain in the ass, and should be more easily cross-compilable and installable via Brew once builds ship based on LLVM 11.~~
- [X] Homebrew support for M1 silicon
  - mostly works, but need a story around supporting both ARM and Intel installs
- [x] Docker support for M1 silicon

**Comment by skylineproject** [comment]
I'm setting up an M1 Mini using mstrap, got a few observations to share. Clearly, as Crystal gets Apple Silicon support, things will be different, but even with Rosetta, things run pretty smoothly.

- I initially ran into [an issue](https://gist.github.com/skylineproject/21cd2d9d82678f5d8f3e539a05effc96) ostensibly related to the OpenSSL version that comes on the M1 Macs, but by [installling Homebrew via Rosetta 2](https://stackoverflow.com/questions/64882584/how-to-run-the-homebrew-installer-under-rosetta-2-on-m1-macbook) and installing that version of OpenSSL, I was able to proceed
- Failing that, manually downloading `strap.sh`  into `~/.mstrap/vendor/strap.sh` should help too
- Project config works great!

Good stuff! Excited to check things out again as the M1 sees wider support from other parts of the ecosystem.

**Comment by maxfierke** [comment]
Closing this finally. Will be released in v0.5.0 in a few minutes.
